kind: pipeline
name: install and test

steps:
  - name: install
    image: node
    commands:
      - npm ci
  - name: build-less-and-attributions
    image: node
    commmands:
      - npm install -g yarn
      - npm run premake
      - npm run attributions
  - name: run-tests
    image: node:buster
    commands:
      - npm ci
      - apt-get update && apt-get install -y xvfb libxtst6 libxss1 libgtk2.0-0 libnss3 libasound2 libgconf-2-4
      - export DISPLAY=:99.0
      - Xvfb :99.0 -ac -screen scrn 1024x768x24 -nolisten tcp &
      - sleep 10
      - npm test
  - name: build
    image: node:buster
    commands:
      - apt-get update && apt-get install -y rpm fakeroot dpkg
      - npm run make
