language: node_js
node_js: '8'
dist: xenial
sudo: required
matrix:
  include:
    - dist: xenial
      addons: 
        apt:
          packages:
            - rpm
            - fakeroot
            - dpkg
      script:
        - npm test
        - travis_wait electron-forge make -p linux
    - os: windows
      script: 
        - travis_wait 50 electron-forge make -p win32
    - os: osx
      addons:
        homebrew:
          packages:
            - 
          update: true
      script: 
        - travis_wait electron-forge make -p darwin
install:
  - npm install
  - npm install -g electron-forge
  - npm install -g yarn